### ISSUE TITLE
[[]]Cannot use keyboard preview

### ISSUE THREAD

**Issue by ydivho12123** [rcvd/logseq-craft-theme#2]
when [[]] is used, only the mouse is used to slide down the preview content, and the view box is moved down with PgDn and will not follow the preview down.But other themes don't have this problem

**Comment by rcvd** [comment]
Could you provide a screenshot? I'm not sure what exactly you are talking about. Thanks.

**Comment by ydivho12123** [comment]
> Could you provide a screenshot? I'm not sure what exactly you are talking about. Thanks.

![image](https://user-images.githubusercontent.com/79443545/160291166-dc377a8a-9637-4336-8872-9113c38b0a64.png)
emmmm  Normally, when you press PgDn, the scroll bar will move down. You can always see the focus. But there seems to be a bug, the line of sight does not follow the focus, and you can't use the keyboard to do this. You can only use the mouse Scroll the wheel to find below

**Comment by rcvd** [comment]
Should be fixed now.
